[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
rustflags = ["-C target-cpu=native"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"


[dependencies]