[package]
name = "rust-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
rustflags = ["-C target-cpu=native"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true

[[bin]]
name = "repl"
path = "src/repl/main.rs"

[[bin]]
name = "compiler"
path = "src/compiler/main.rs"

[lib]
mame = "common"
path = "src/common/lib.rs"


[dependencies]