[package]
name = "jniLib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vipl = { path = "../.." }
jni = { version = "0.21.1", features = ["invocation"] }

[lib]
crate_type = ["cdylib"]